name: Daily Workflow
on:
  schedule:
    # Runs daily at midnight UTC
    - cron: "*/5 * * * *"
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: lsiiiiiiiiiijiiiiiiiiiiiiii
        run: ls -l
      - name: Run script
        run: ls -l&&sudo python3 bing_wallpaper.py >> log.log
      - name: Print log
        run: tail -f log.log -n100
